name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: |
        npm init -y
        npm install --save-dev css-tree acorn
    
    - name: Validate CSS
      run: |
        node -e "
        const fs = require('fs');
        const csstree = require('css-tree');
        try {
          const css = fs.readFileSync('styles.css', 'utf8');
          csstree.parse(css);
          console.log('✓ CSS is valid');
        } catch (e) {
          console.error('✗ CSS validation failed:', e.message);
          process.exit(1);
        }
        "
    
    - name: Validate JavaScript
      run: |
        node -e "
        const fs = require('fs');
        const acorn = require('acorn');
        try {
          const js = fs.readFileSync('app.js', 'utf8');
          acorn.parse(js, { ecmaVersion: 2020 });
          console.log('✓ JavaScript is valid');
        } catch (e) {
          console.error('✗ JavaScript validation failed:', e.message);
          process.exit(1);
        }
        "
    
    - name: Test HTML loads properly
      run: |
        node -e "
        const fs = require('fs');
        const html = fs.readFileSync('json_table.html', 'utf8');
        if (!html.includes('styles.css')) {
          console.error('✗ HTML does not reference styles.css');
          process.exit(1);
        }
        if (!html.includes('app.js')) {
          console.error('✗ HTML does not reference app.js');
          process.exit(1);
        }
        console.log('✓ HTML references external files correctly');
        "

  deploy:
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    needs: validate
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: .
        branch: gh-pages
        clean: true