name: Deploy to GitHub Pages
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      branch:
        description: 'Branch to checkout'
        required: false
        default: 'master'
        type: string

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
          ref: ${{ inputs.branch }}

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: .
        branch: gh-pages
        clean: true
